### ISSUE TITLE
Hawaii GFS Wave Model

### ISSUE THREAD

**Issue by jamesthesken** [mpiannucci/surfpy#19]
Thank you for making this awesome library! I was looking through the examples and I wanted to take a crack at supporting Hawaii.

What other modifications would be needed aside from adding a new function as shown in `wavemodel.py`:

```
def us_west_coast_gfs_wave_model():
    return WaveModel(
        name='gfswave',
        subset='wcoast.0p16',
        description='GFS Wave Model: US West Coast 0.16 degree',
        bottom_left=Location(25.00, 210.00),
        top_right=Location(50.00005, 250.00008),
        location_resolution=0.167,
        time_resolution=0.125,
        max_index=384,
        hourly_cutoff_index=0
    )
```

If you have any pointers in the right direction that would be awesome. I am hoping to build a small forecasting app with FastAPI so hopefully there's ways I can help the project.

Thank you,
James

**Comment by mpiannucci** [comment]
You would just add a new function like the west coast one that returns the Hawaiian/EPAC wave model and that will get you started! Let me know if you hit issues with that

**Comment by jamesthesken** [comment]
Thank you @mpiannucci I was able to use the EPAC model, but I didn't see any available for Hawaii specifically. Not too familiar with this field but I'll see how this model does at forecasting my homebreak. Thank you again

**Comment by mpiannucci** [comment]
Cheers!! Good luck and let me know if you make anything cool!
