### ISSUE TITLE
ModuleNotFoundError: No module named 'grippy'

### ISSUE THREAD

**Issue by vbartle** [mpiannucci/surfpy#7]
You should probably submit grippy to pip or include it in this project. I am assuming grippy is your other library: https://github.com/mpiannucci/grippy

Actually not sure why the dependency for grippy you included didn't get detected but I had to manually download and pip install it (https://github.com/mpiannucci/grippy/tarball/master#egg=grippy-0.1.0).

**Comment by mpiannucci** [comment]
Yeah thats weird, if you build with setup.py it should install automatic I think

**Comment by vbartle** [comment]
Running setup.py returned the error in the title, unfortunately. Not sure what the fix is but if someone else runs into this maybe they'll see this thread.

**Comment by mpiannucci** [comment]
Thanks @vbartle Ill take a look soon to make sure I didnt miss anything obvious
