### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by BuffaloWill** [mpiannucci/surfpy#9]
Thank you for this interesting project.

Where would I find the data needed to customize these lines to a different break/beach:
https://github.com/mpiannucci/surfpy/blob/695cb0f873e5570f319327fc7a086b5d330933fb/examples/fetch_forecast.py#L6-L9

Depth, angle, and slope have me stumped.

**Comment by mpiannucci** [comment]
The depth you would get from bathymetry charts. You can usually get them from here https://maps.ngdc.noaa.gov/viewers/bathymetry/

The angle is the prime swell direction for the given location. In my example, 145 degrees is the prime direction for swell in the forecast location. This is not super robust, just a guess. Future work could make this more detailed. 

The slope is the slope of the seabed towards the breaking zone. I just approximate here (again) and use a 1/50 grade slope which is pretty average. It will vary by how close to hsore you are and the bathemetry of the area you want to forecast. Again this part is not super robust and pretty averaged.

**Comment by mpiannucci** [comment]
Gunna close this because i havent heard back. Reach out if you need more help!
